services:

  db:
    image: mariadb:10
    container_name: db
    volumes:
      - ./db_data:/var/lib/mysql
      - ./backups:/backups
    environment:
      MYSQL_DATABASE: wpgdemo
      MYSQL_USER: wpgdemo_user
      MYSQL_PASSWORD: wpgdemo_user
      MYSQL_ROOT_PASSWORD: toor
      
  wordpress:
    image: wordpress:5.9.3-php7.4
    container_name: wp
    depends_on: ['db']
    ports: ['85:80']
    links: ['db:db']
    volumes:
      - ./wp-data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wpgdemo
      WORDPRESS_DB_USER: wpgdemo_user
      WORDPRESS_DB_PASSWORD: wpgdemo_user

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: phpmyadmin
    depends_on: ['db']
    ports: ['12000:80']
    links: ['db:db']
    environment:
      - PMA_HOST=db
      - PMA_USER=wpgdemo_user
      - PMA_PASSWORD=wpgdemo_user


volumes:
  db_data: {}
